version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: carhabty-app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    environment:
      APP_ENV: prod
      APP_DEBUG: 0
    depends_on:
      - db
    restart: always

  web:
    image: nginx:alpine
    container_name: carhabty-web
    ports:
      - "8080:80"  # ton site accessible sur http://vps-ip:8080
    volumes:
      - .:/var/www/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    restart: always

  db:
    image: mysql:8.0
    container_name: carhabty-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: carhabty
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3307:3306"  # si 3306 est déjà utilisé sur ton VPS
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data:
