services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: carhabty-app
    ports:
      - "8080:80"            # ton site sera accessible sur http://vps-ip:8080
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    restart: always

  db:
    image: mysql:8.0
    container_name: carhabty-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: carhabty
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3307:3306"          # changer le port si 3306 est déjà utilisé sur ton VPS
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: carhabty-phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - "8081:80"            # phpMyAdmin accessible sur http://vps-ip:8081
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

volumes:
  db_data:
