version: "3.9"

services:
  app:
    image: php:8.2-apache
    container_name: carhabty-app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./html:/var/www/html
      - /etc/letsencrypt/live/essayara.com/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/essayara.com/privkey.pem:/etc/ssl/private/privkey.pem:ro
      - ./html/apache/default-ssl.conf:/etc/apache2/sites-available/default-ssl.conf:ro
    command: >
      bash -c "\
        a2enmod ssl rewrite headers && \
        a2ensite default-ssl.conf && \
        a2dissite 000-default.conf && \
        apache2-foreground"
    restart: always

  db:
    image: mysql:8.0
    container_name: carhabty-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: carhabty
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: carhabty-phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: /bin/sh
    command: -c "sleep infinity"
    restart: unless-stopped

volumes:
